#
# [389] Find the Difference
#
# https://leetcode.com/problems/find-the-difference/description/
#
# algorithms
# Easy (51.56%)
# Total Accepted:    110.3K
# Total Submissions: 213.8K
# Testcase Example:  '"abcd"\n"abcde"'
#
# 
# Given two strings s and t which consist of only lowercase letters.
# 
# String t is generated by random shuffling string s and then add one more
# letter at a random position.
# 
# Find the letter that was added in t.
# 
# Example:
# 
# Input:
# s = "abcd"
# t = "abcde"
# 
# Output:
# e
# 
# Explanation:
# 'e' is the letter that was added.
# 
#
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dic = {}
        
        for c in s:
            if c not in dic:
                dic[c] = 1
            else:
                dic[c] += 1
        
        for c in t:
            if c not in dic:
                return c
            else:
                dic[c] -= 1
                
        for c in dic.keys():
            if dic[c] < 0:
                return c
        
    
            
        
